# shared across all TinySol runs
n_classes: 14
n_scales: 9
base_channels: 1
d_model: 32
nhead: 2
ff_mult: 4
depth_per_scale: 1

frontend:
  name: murenn
  stride: 128
  octaves: [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8]
  Q_multiplier: 16
  include_scale: false

# training defaults
epochs: 1000
lr: 0.003
wd: 0.05
seed: 1337

data:
  root: "/Users/user/Documents/Tinysol-master"
  batch_size: 32
  num_workers: 4
  sample_rate: 44100
  fold: 1
  segment_seconds: 5.0