sample_rate: 16000
n_scales: 6
base_channels: 64
d_model: 64
hop: 32
local_window: 64
nhead: 8
ff_mult: 4
depth_per_scale: 1
global_depth: 2
n_classes: 50
scale_dropout_p: 0.2 

frontend:
  name: murenn
  # DTCWT Student-style params:
  stride: 128
  # counts per level are inferred from how many times each level index appears here
  # (this example yields Q_0=1, Q_1=2, Q_2=3)
  octaves: [0, 1, 1, 2, 2, 2]
  #octaves: [-1,  9,  9,  9,  8,  8,  8,  7,  7,  7,  6,  6,  6,  5,  5,  5,  4, 4,  4,  3,  3,  3,  2,  2,  2,  1,  1,  1,  0,  0,  0,  0]
  Q_multiplier: 16
  include_scale: false
