sample_rate: 44100
n_scales: 6
base_channels: 16
d_model: 16
hop: 32
nhead: 4
ff_mult: 4
depth_per_scale: 4
global_depth: 2
n_classes: 14
scale_dropout_p: 0.

frontend:
  name: murenn
  # DTCWT Student-style params:
  stride: 512
  # counts per level are inferred from how many times each level index appears here
  # (this example yields Q_0=1, Q_1=2, Q_2=3)
  octaves: [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5]
  #octaves: [-1,  9,  9,  9,  8,  8,  8,  7,  7,  7,  6,  6,  6,  5,  5,  5,  4, 4,  4,  3,  3,  3,  2,  2,  2,  1,  1,  1,  0,  0,  0,  0]
  Q_multiplier: 8
  include_scale: false
