# shared across all ESC-50 runs
n_classes: 50
n_scales: 6
base_channels: 4
d_model: 64
nhead: 8
ff_mult: 4
depth_per_scale: 2

frontend:
  name: murenn
  stride: 256
  octaves: [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5]
  Q_multiplier: 16
  include_scale: false

# training defaults
epochs: 100
lr: 0.0005
wd: 0.005
seed: 1337

data:
  root: "/Users/user/Documents/ESC-50-master"  
  batch_size: 32
  num_workers: 4
  sample_rate: 44100
  fold: 1
  segment_seconds: 5.0