arch: mel_cnn

epochs: 120
lr: 0.0005
wd: 0.05
dropout: 0.1
cnn_width: 16

# mel settings
mel:
  n_mels: 64
  # leave n_fft/hop_length None to auto-pick from sample_rate
  specaug_p: 0.5
  freq_mask_param: 12
  time_mask_param: 24
  rms_norm: false
  rms_target: 0.1